package localization;

import java.util.ListResourceBundle;

public class Resource_it_IT extends ListResourceBundle {
    public static final Object[][] contents = {
            {"insert", "inserire"},
            {"show", "mostrare"},
            {"help", "aiuto"},
            {"info", "Informazioni"},
            {"clear", "chiaro"},
            {"execute script", "eseguire lo script"},
            {"count greater semester", "Contare il semestre più grande"},
            {"filter less students count", "Filtro meno studenti contano"},
            {"remove greater key", "Rimuovere la chiave maggiore"},
            {"log out", "disconnettersi"},
            {"remove key", "Rimuovere la chiave"},
            {"remove lower", "Rimuovere in basso"},
            {"replace if greater", "Sostituire se maggiore"},
            {"update", "aggiornare"},
            {"id", "un ID"},
            {"name", "nome"},
            {"coordinates", "coordinate"},
            {"creation date", "data di creazione"},
            {"students count", "Gli studenti contano"},
            {"expelled students", "studenti espulsi"},
            {"should be expelled", "dovrebbe essere espulso"},
            {"semester", "semestre"},
            {"admin", "amministratore"},
            {"height", "altezza"},
            {"hair color", "colore dei capelli"},
            {"nationality", "nazionalità"},
            {"location", "Posizione"},
            {"user", "user"},
            {"Novikov & Vinogradov lab8", "Novikov e Vinogradov Lab8"},
            {"login", "un accesso"},
            {"password", "parola d'ordine"},
            {"sign up", "iscrizione"},
            {"log in", "accesso"},
            {"this field is required", "Questo campo è obbligatorio"},
            {"incorrect login/password", "Accesso/password errato"},
            {"Server error, try again!", "Errore del server, riprova!"},
            {"User with this login already exists", "Utente con questo accesso già esiste"},
            {"help", "aiuto"},
            {"info", "Informazioni"},
            {"show", "mostrare"},
            {"insert", "inserire"},
            {"clear", "chiaro"},
            {"execute script", "eseguire lo script"},
            {"count greater semester", "Contare il semestre più grande"},
            {"filter less students count", "Filtro meno studenti contano"},
            {"remove greater key", "Rimuovere la chiave maggiore"},
            {"log out", "disconnettersi"},
            {"remove key", "Rimuovere la chiave"},
            {"remove lower", "Rimuovere in basso"},
            {"replace if greater", "Sostituire se maggiore"},
            {"update", "aggiornare"},

            {"help", "aiuto"},
            {"info", "Informazioni"},
            {"show", "mostrare"},
            {"insert (key) {element}", "insert (key) {element}"},
            {"clear", "chiaro"},
            {"execute script (file path)", "Esegui script (percorso del file)"},
            {"count greater semester (semester)", "Contare il semestre più grande (semestre)"},
            {"filter less students count (students count)", "Filtro meno studenti contano (contano gli studenti)"},
            {"remove greater key (key)", "Rimuovere la chiave maggiore (chiave)"},
            {"log out", "disconnettersi"},
            {"remove key (key)", "Rimuovi il tasto (tasto)"},
            {"remove lower {element}", "Rimuovi il numero inferiore {elemento}"},
            {"replace if greater (key) {element}", "Sostituisci se maggiore (chiave) {elemento}"},
            {"update (id) {element}", "aggiornamento (id) {elemento}"},
            {"sum of students count", "Somma degli studenti contano"},


            {"information about the collection", "informazioni sulla raccolta"},
            {"information about commands", "informazioni sui comandi"},
            {"shows map representation of collection", "mostra la rappresentazione della mappa della raccolta"},
            {"to add an element to the collection", "Per aggiungere un elemento alla collezione"},
            {"to delete all elements from the collection", "Per eliminare tutti gli elementi dalla collezione"},
            {"to execute command sequence", "Per eseguire comandi segnante"},
            {"to count elements that have bigger semester", "per contare elementi che hanno un semestre più grande"},
            {"to filter all elements with lower students count", "per filtrare tutti gli elementi con gli studenti inferiori contano"},
            {"to remove all elements with greater key", "Per rimuovere tutti gli elementi con una chiave maggiore"},
            {"to return to login page", "Per restituire la pagina di accesso"},
            {"to remove element by key", "Per rimuovere l'elemento per chiave"},
            {"to remove all elements that are lower than given", "per rimuovere tutti gli elementi inferiori a quelli dati"},
            {"to replace the element if the new one is greater", "per sostituire l'elemento se quello nuovo è maggiore"},
            {"to update the element", "Per aggiornare l'elemento"},

            {"answer:", "rispondere:"},
            {"wrong parameter", "parametro errato"},
            {"parameter", "parametro"},
            {"input semester", "inserisci il semestre"},
            {"send", "inviare"},
            {"error", "errore"},
            {"collection cleaned", "raccolta pulita"},
            {"no elements in collection", "nessun elemento nella collezione"},
            {"element with this key already exists", "Elemento con questa chiave già esiste"},
            {"element added to the collection", "Elemento aggiunto alla raccolta"},
            {"element was not added to the collection", "L'elemento non è stato aggiunto alla collezione"},
            {"key", "chiave"},
            {"input students count", "Gli studenti di input contano"},
            {"input key", "Chiave di input"},
            {"success", "successo"}



    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
